fix typo 'sesson' to 'season'
orange-alliance/TOA-Flutter pull request #26
Opened 2020-11-08 23:13 UTC by khari05

2020-11-08 23:15 UTC, ofekashery requested changes

2020-11-08 23:15 UTC, ofekashery commented on lib/models/match.dart
> +  String getseasonKey() {
Use ``getSeasonKey`` instead.

2020-11-08 23:26 UTC, khari05 commented on lib/models/match.dart
> +  String getseasonKey() {
added a commit with the fix

2020-11-09 18:48 UTC, nholo1332 approved these changes

2020-11-09 18:51 UTC, merged